sudo: false

language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - frontend/node_modules
    - backend/node_modules

script:
  - npm run build-projects
  - npm run lint-projects
