sudo: false

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules
    - frontend/node_modules
    - backend/node_modules

install:
  - yarn install

script:
  - yarn run build-projects
  - yarn run lint-projects
